backend:
  name: github
  repo: saber-studios/saber-studios.github.io
  branch: main   # or master  
  client_id: Ov23liTEEvIln92HJCxZ
  base_url: https://sveltia-cms-auth.quint-john.workers.dev/

site_url: https://saber-studios.github.io

media_folder: "/assets/upload"
public_folder: "/assets/upload"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description for SEO", name: "description", widget: "string", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false, field: { name: text, label: Text, widget: string } }
      - { label: "Tags", name: "tags", widget: "list", required: false, field: { name: text, label: Text, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
